f = open('lakefile.lean', 'w', encoding='utf-8')
f.write('import Lake\n')
f.write('open Lake DSL\n')
f.write('\n')
f.write('package \u00abOuroborosVerifier\u00bb where\n')
f.write('\n')
f.write('require mathlib from git\n')
f.write('  "https://github.com/leanprover-community/mathlib4.git"\n')
f.write('\n')
f.write('@[default_target]\n')
f.write('lean_lib \u00abOuroborosVerifier\u00bb where\n')
f.close()
print('done')