"""
Calculus environments for OUROBOROS.

FundamentalTheoremEnvironment:
  Generates a sequence f(t) and asks agents to discover F(t) where F'(t) = f(t).
  The ground truth: F(t) = INTEGRAL(f)[t] = Σᵢ₌₀ᵗ f(i)
  The key relationship: DERIV(INTEGRAL(f)) ≈ f

  This is the Fundamental Theorem of Calculus in discrete form:
    d/dt(∫₀ᵗ f(x)dx) = f(t)

  If an agent discovers DERIV(INTEGRAL(TIME)) as the expression for a
  sequence generated by f(t) = t (the simplest case), it has discovered
  the FTC empirically.

  More impressive: if it discovers DERIV(INTEGRAL(SIN)) ≈ SIN — showing
  the FTC holds for transcendental functions too.
"""

from __future__ import annotations
import math
from typing import List, Callable
from ouroboros.environments.base import Environment


class FundamentalTheoremEnv(Environment):
    """
    obs[t] = cumsum(f)[t] = Σᵢ₌₀ᵗ f(i)
    
    The integrand f is given; the agent must discover F(t) = ∫f.
    Equivalently: agent finds F s.t. DERIV(F) ≈ f.
    
    Ground truth: F(t) = CUMSUM(f)[t]
    Expression: INTEGRAL(f_expr)
    
    If agent correctly identifies F, then DERIV(F) should reproduce f.
    """

    def __init__(
        self,
        f_name: str = "identity",
        modulus: int = None,
        seed: int = 42,
    ):
        """
        f_name: which integrand function to use
          'identity': f(t) = t,      F(t) = t(t+1)/2
          'constant': f(t) = 1,      F(t) = t
          'sine':     f(t) = sin(t/7), F(t) = cumsum(sin)
          'square':   f(t) = t²,     F(t) = t(t+1)(2t+1)/6
        """
        super().__init__(name=f"FundamentalTheoremEnv({f_name})", seed=seed)
        self.f_name = f_name
        self.modulus = modulus
        self._cache: List[float] = []
        self._build_cache(2000)

    def _f(self, t: int) -> float:
        """The integrand function f(t)."""
        if self.f_name == "identity":
            return float(t)
        if self.f_name == "constant":
            return 1.0
        if self.f_name == "sine":
            return math.sin(t / 7.0)
        if self.f_name == "square":
            return float(t * t)
        if self.f_name == "linear":
            return 2.0 * t + 1.0
        return float(t)

    def _build_cache(self, n: int) -> None:
        running_sum = 0.0
        for t in range(n):
            running_sum += self._f(t)
            val = running_sum
            if self.modulus:
                val = val % self.modulus
            self._cache.append(val)

    def generate(self, length: int, start: int = 0) -> List[float]:
        if start + length > len(self._cache):
            self._build_cache(start + length + 100)
        return self._cache[start:start + length]

    @property
    def alphabet_size(self) -> int:
        if self.modulus:
            return self.modulus
        return int(max(abs(v) for v in self._cache[:200])) + 2

    def ground_truth_expression(self) -> str:
        return f"INTEGRAL(f_{self.f_name})"

    def ftc_check_expression(self) -> str:
        """Expression that SHOULD reproduce f when DERIV is applied to the output."""
        return f"DERIV(INTEGRAL(f_{self.f_name})) ≈ {self.f_name}(t)"

    def verify_ftc_holds(self, predictions: List[float], tolerance: float = 0.1) -> float:
        """
        Check if DERIV of predictions ≈ the original f.
        Returns: fraction of steps where |DERIV(pred)[t] - f(t)| < tolerance
        """
        derivs = [predictions[t] - predictions[t-1] for t in range(1, len(predictions))]
        f_vals = [self._f(t) for t in range(1, len(predictions))]
        n_correct = sum(1 for d, f in zip(derivs, f_vals) if abs(d - f) < tolerance)
        return n_correct / max(len(derivs), 1)


class AntiderivativeEnv(Environment):
    """
    obs[t] = f(t) where agents must find F s.t. F' = f.
    
    This is the reverse of FundamentalTheoremEnv:
    Given: f(t) (the derivative)
    Find:  F(t) (the antiderivative)
    
    Ground truth: F(t) = INTEGRAL(f)
    
    This directly tests whether agents use INTEGRAL_NODE.
    """

    def __init__(self, f_name: str = "identity", seed: int = 42):
        super().__init__(name=f"AntiderivativeEnv({f_name})", seed=seed)
        self.f_name = f_name

    def _f(self, t: int) -> float:
        if self.f_name == "identity":
            return float(t)
        if self.f_name == "constant":
            return 3.0
        if self.f_name == "sine":
            return math.sin(t / 7.0)
        return float(t)

    def generate(self, length: int, start: int = 0) -> List[float]:
        """Returns the INTEGRAND, not the integral."""
        return [self._f(t) for t in range(start, start + length)]

    @property
    def alphabet_size(self) -> int:
        return 50


class CalculusDiscoveryRunner:
    """
    Tests whether OUROBOROS agents discover calculus relationships.
    
    Key tests:
    1. Can agents predict F(t) = Σᵢ₌₀ᵗ f(i) using INTEGRAL_NODE?
    2. Does DERIV(prediction) ≈ f(t) — FTC holds for discovered expression?
    3. Does INTEGRAL(DERIV(F)) ≈ F — inverse FTC?
    """

    def run_ftc_test(self, verbose: bool = True) -> dict:
        """Run the fundamental theorem of calculus test."""
        from ouroboros.nodes.extended_nodes import ExtExprNode, ExtNodeType
        from ouroboros.synthesis.expr_node import NodeType

        results = {}

        def time_e():
            n = ExtExprNode.__new__(ExtExprNode)
            n.node_type = NodeType.TIME; n.value = 0.0
            n.lag = 1; n.state_key = 0; n.window = 10
            n.left = n.right = n.third = None; n._cache = {}
            return n

        for f_name in ["identity", "constant", "linear"]:
            env = FundamentalTheoremEnv(f_name=f_name)
            true_vals = env.generate(50)

            # Build the target expression: INTEGRAL(TIME) for identity
            # INTEGRAL(CONST(1)) for constant, etc.
            if f_name == "identity":
                from ouroboros.synthesis.expr_node import NodeType
                inner = time_e()
            elif f_name == "constant":
                inner = ExtExprNode.__new__(ExtExprNode)
                inner.node_type = NodeType.CONST; inner.value = 1.0
                inner.lag = 1; inner.state_key = 0; inner.window = 10
                inner.left = inner.right = inner.third = None; inner._cache = {}
            else:
                inner = time_e()  # simplified

            integral_expr = ExtExprNode(ExtNodeType.INTEGRAL, left=inner)

            # Evaluate
            predictions = []
            for t in range(50):
                pred = integral_expr.evaluate(t, [], {})
                predictions.append(pred)

            # Check FTC: DERIV(predictions) ≈ f(t)
            ftc_accuracy = env.verify_ftc_holds(predictions, tolerance=0.5)
            match_accuracy = sum(
                1 for p, a in zip(predictions, true_vals) if abs(p - a) < 0.5
            ) / 50

            results[f_name] = {
                "ftc_accuracy": ftc_accuracy,
                "match_accuracy": match_accuracy,
                "predictions_0_5": predictions[:5],
                "true_0_5": true_vals[:5],
            }

            if verbose:
                print(f"\nFTC test ({f_name}):")
                print(f"  INTEGRAL({f_name})[0:5] = {[f'{p:.1f}' for p in predictions[:5]]}")
                print(f"  True F[0:5]             = {[f'{v:.1f}' for v in true_vals[:5]]}")
                print(f"  Match accuracy: {match_accuracy:.2%}")
                print(f"  FTC accuracy (DERIV≈f): {ftc_accuracy:.2%}")

        return results